image: python:3.8
pipelines:
  default:
      - step:
          name: Lint code
          caches: [pants]
          script:
            - env | grep BITBUCKET
            - PANTS_CONFIG_FILES=pants.ci.toml ./pants version
            - "PANTS_CONFIG_FILES=pants.ci.toml  ./pants lint ::"

definitions:
  caches:
    pants: ~/.cache/pants