image: python:3.8

pipelines:
  default:
    - parallel:
      - step:
          name: Bootstrap Pants
          caches: [pants]
          script:
            - ./pants version
      - step:
          name: Lint code
          caches: [pants]
          script:
            - "./pants lint ::"

definitions:
  caches:
    pants: ~/.cache/pants