[GLOBAL]
pants_version = "2.6.0rc2"
pantsd = false

backend_packages.add = [
  "pants.backend.python",
]

plugins = [
  "toolchain.pants.plugin==0.13.1",
]

[source]
root_patterns = ["/"]

[python-setup]
interpreter_constraints = [">=3.8"]
requirement_constraints = "constraints.txt"
interpreter_search_paths = ["<PATH>", "<PYENV>"]

[anonymous-telemetry]
enabled = false


[toolchain-setup]
repo = "minimal-pants"

[buildsense]
enable = false
