[GLOBAL]
pants_version = "2.6.0"
pantsd = false
# level = "debug"

backend_packages.add = [
  "pants.backend.project_info",
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
]

plugins = [
  "toolchain.pants.plugin==0.14.0.dev1",
]

[python-repos]
indexes.add = ["https://test.pypi.org/simple/"]

[source]
root_patterns = ["/"]

[python-setup]
interpreter_constraints = [">=3.8"]
requirement_constraints = "constraints.txt"
interpreter_search_paths = ["<PATH>", "<PYENV>"]

[anonymous-telemetry]
enabled = false


[toolchain-setup]
repo = "minimal-pants"

[buildsense]
enable = false
