[GLOBAL]
pants_version = "2.5.0"
pantsd = false

[source]
root_patterns = [ "/",]

[python-setup]
interpreter_constraints = [ ">=3.8",]
requirement_constraints = "constraints.txt"
interpreter_search_paths = [ "<PATH>", "<PYENV>",]

[anonymous-telemetry]
enabled = false

[GLOBAL.backend_packages]
add = [ "pants.backend.python",]
