[GLOBAL]
pants_version = "2.7.0rc4"
pantsd = false
# level = "debug"

backend_packages.add = [
  "pants.backend.project_info",
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.experimental.python",
]

plugins = [
  "toolchain.pants.plugin==0.14.0",
]

# [python-repos]
# indexes.add = ["https://test.pypi.org/simple/"]

[source]
root_patterns = ["/"]

[python-setup]
interpreter_constraints = [">=3.8"]
requirement_constraints = "constraints.txt"
interpreter_search_paths = ["<PATH>", "<PYENV>"]

[anonymous-telemetry]
enabled = false

[black]
version = "black==21.8b0"

[isort]
version = "isort[pyproject]==5.9.3"

[flake8]
version = "flake8==3.9.2"
extra_requirements.add = [
  "flake8-debugger",
  "flake8-2020",
  "flake8-mutable",
  "flake8-comprehensions",
  "flake8-bugbear",
  "flake8-executable"
]


[toolchain-setup]
repo = "minimal-pants"


[buildsense]
enable = false
